### ISSUE TITLE
Artwork setting

### ISSUE THREAD

**Issue by PierreDurrr** [lostb1t/replex#109]
Would it be possible to set a custom artwork for hero style cards ?
I was thinking to a way to specifying artwork, and fallback to plex/tmdb whatever source you use currently ? Like if custom artwork is set in plex, use it, then fallback if no custom art found.
Would something like this feasible ?

**Comment by lostb1t** [comment]
theres a poster and background field avaiable in plex. Thing is both are used in plex and dont really fit the hero style. So theres not really a way to define custom heros.

also this should
be in discussions. closing
