### ISSUE TITLE
ERROR salvo_proxy: get response data failed error

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#111]
`2023-12-30T20:58:32.274665Z ERROR salvo_proxy: get response data failed error=Other(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(84.66.184.56)), port: Some(32400), path: "/:/websockets/notifications", query: Some("X-Plex-Token=******************"), fragment: None }, source: hyper::Error(IncompleteMessage) }) uri=http://plex.plexified.co.uk/:/websockets/notifications?X-Plex-Token=***********************`

Not sure whats causing this? I can't play anything on the server, everything loads but nothing plays.

**Comment by jl94x4** [comment]
Nothing appears to be merged either, but the HERO cards seem to work.

**Comment by eandrade92630** [comment]
I use a load balancer on my server and fall back to Plex directly if the connection to replex fails. Today I noticed my hero rows were gone and checked the logs and noticed I was getting this as well.

**Comment by Lokilicious** [comment]
I also get this constantly

**Comment by jl94x4** [comment]
This is still a real big issue

**Comment by eandrade92630** [comment]
> This is still a real big issue 

I'm curious, is this actually affecting you in any way? I see this all the time but I've only had it cause problems once.

**Comment by lostb1t** [comment]
duplicate #101
