### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by PilaScat** [lostb1t/replex#112]
when I found this project I couldn't wait to put it together but two hours have already passed and nothing is working
tried local or remote with reverse proxy but nothing, it does not merge rows with the same name
i'm on unraid, plex docker on host and replex on docker-network (customized only the name)
npm is on docker network
here my docker run
```
docker run
  --name='Replex'
  --net='docker-network'
  -e 'REPLEX_HOST'='http://192.168.1.20:32400'
  -e 'REPLEX_CACHE_TTL '='1800'
  -e 'REPLEX_CACHE_ROWS'='true'
  -e 'REPLEX_CACHE_ROWS_REFRESH'='true'
  -e 'REPLEX_REDIRECT_STREAMS'='true'
  -e 'REPLEX_REDIRECT_STREAMS_HOST'='http://public-ddns:32400'
  -e 'REPLEX_VIDEO_TRANSCODE_FALLBACK_FOR'='"1080"'
  -e 'REPLEX_HERO_ROWS'=''
  -p '32450:80/tcp' 'ghcr.io/lostb1t/replex:latest'
```

**Comment by jl94x4** [comment]
```docker run -d --name=replex --rm -it -p 90:80 -e REPLEX_HOST="http://ip.0:32400" -e REPLEX_REDIRECT_STREAMS=true -e REPLEX_DISABLE_RELATED=true -e REPLEX_INCLUDE_WATCHED=true  -e REPLEX_HERO_ROWS=tv.toprated,tv.inprogress -e REPLEX_CACHE_ROWS=true -e REPLEX_CACHE_ROWS_REFRESH=true -e REPLEX_CACHE_TTL=0 ghcr.io/lostb1t/replex:latest```

Run this, point your domain to http://ip:90

Put in your domain in the network tab, restart Plex

Profit

**Comment by PilaScat** [comment]
I have a somewhat particular setup, that's why it didn't work immediately, then it doesn't have to go through cloudflare so I have to use redirect.
But now some clients have problem (iOS and PS4) and I have not a secure connection (but I have SSL with NPM)

**Comment by jl94x4** [comment]
> I have a somewhat particular setup, that's why it didn't work immediately, then it doesn't have to go through cloudflare so I have to use redirect. But now some clients have problem (iOS and PS4) and I have not a secure connection (but I have SSL with NPM)

None of my devices have a secure connection...

I am also using NPM with Lets Encrypt SSL.
