### ISSUE TITLE
Can curl be included in replex docker?

### ISSUE THREAD

**Issue by eandrade92630** [lostb1t/replex#115]
I use auto heal to auto restart docker containers in poor health. If possible could you include curl in the dockerfile? My purpose for this would be to curl Plex through replex and if unable to get a proper response replex would auto restart. It would help with situations like this https://github.com/lostb1t/replex/issues/111#issue-2060856189 where I had to restart the container due to this issue.

**Comment by lostb1t** [comment]
you can extend the base image and add curl there

untested example:
 
```
FROM ghcr.io/lostb1t/replex
RUN apt update && \
    apt -y curl
```
