### ISSUE TITLE
Secure Connections through REPLEX

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#116]
For some reason, when going through REPLEX my Plex connections are not secure.

Using nginx-proxy-manager to get SSL certs on my domain http://replex.plexified.co.uk (it has SSL according to the link) but all plex streams are "Not Secure".

Any reason for this?

```
docker run --rm -it -p 90:80 -e REPLEX_HOST="http://ip:32400" -e REPLEX_REDIRECT_STREAMS=true -e REPLEX_DISABLE_RELATED=true -e REPLEX_INCLUDE_WATCHED=true  -e REPLEX_HERO_ROWS=tv.toprated,tv.inprogress -e REPLEX_CACHE_ROWS=true -e REPLEX_CACHE_ROWS_REFRESH=true -e REPLEX_CACHE_TTL=0 ghcr.io/lostb1t/replex:latest```

**Comment by PilaScat** [comment]
same

**Comment by jl94x4** [comment]
> same

How is your set up?

**Comment by eandrade92630** [comment]
"not secure" is kind of confusing. As long as your connection is https (SSL/TLS encrypted) you're fine. The "secure"/padlock only works for the internal network not with reverse proxies. It can't actually tell if it's secure or not.

**Comment by lostb1t** [comment]
@eandrade92630 is right. Your connection is secure and terminated at your proxy lev. after that its unsecured to your plex server. But thats only on your local network/between containers. So plex sees its as "insecure"

hope that explains it
