### ISSUE TITLE
It doesent work even though it launches fine

### ISSUE THREAD

**Issue by s0len** [lostb1t/replex#119]
Hi, I've lauched the container just fine and i'm able to go to replexs ip: http://192.168.10.98:3001 (that's the ip of my server on my lan). When I ipen that adress, i need to log into plex and afterwards I see my whole library but nothing has changed? 

I'm running truenas scale so i'm deploying the app through a custom app meant for this. Have done so before with other custom docker containers so it should work with yours aswell.

I've made sure GDM is disabled, which is was prior to launching.
Below you'll see a screenshot of the environment variables I've set. 
![Screenshot 2024-01-26 at 14 13 45](https://github.com/lostb1t/replex/assets/35483234/c9c011aa-534a-44af-95d5-95028e28c7de)

The containers log only shows to rows of info:
2024-01-26T13:06:09.094884Z  INFO replex: Replex version 0.20.0
2024-01-26T13:06:09.103399Z  INFO salvo_core::server: listening [HTTP/1.1] on http://0.0.0.0:80

I have no clue as to why nothing happens, do you have or any suggestions?

Thanks

**Comment by jl94x4** [comment]
Same is happening with me, at the moment. Did you find a fix for this @s0len

**Comment by s0len** [comment]
Unfortunately I gave up :( @jl94x4

**Comment by lostb1t** [comment]
for technical support create a discussion. Closing this.
