### ISSUE TITLE
(Plex for Android 10.9.0.5600-beta) Nvidia Shield breaks herostyle artwork on homescreen

### ISSUE THREAD

**Issue by nadsy** [lostb1t/replex#120]
I have noticed that the latest Plex beta for Android (Plex for Android 10.9.0.5600-beta) has broken replexhero artwork on the home screen?

Nvidia Shield client

**Comment by Lokilicious** [comment]
Same happened to my Samsung TV and a friends Hisense TV, it looks like a regular poster crammed into Hero Style.

**Comment by nadsy** [comment]
> Same happened to my Samsung TV and a friends Hisense TV, it looks like a regular poster crammed into Hero Style.

Yup that's exactly what it looks like,

Any word on this @lostb1t ?

Was thinking it might have something to do with the new Plex Rental that's getting pushed out.

**Comment by lostb1t** [comment]
lets wait and see if other clients are affected aswell.

If people are adventurous you can play with client profiles here: https://github.com/lostb1t/replex/blob/a5dc266588739be2a03728669ab988d263168d19/src/transform.rs#L509

just clone the repo and run cargo run from the command line (install rust ofcourse)

'REPLEX_HOST=http://myplex:32400 cargo run'

**Comment by YozoraXCII** [comment]
> well im able to replicate on the latest beta. Problem is... cannot seem to get it right. Home I borked for hero styles. Lets hope it gets fixed before it gets out of beta

I doubt that very much - the 1.32.7 beta had an issue that caused a 500 internal server error, we made them aware and they acknowledged it, rolled it out anyway and then fixed it in 1.32.8 :)

**Comment by lostb1t** [comment]
k i fixed this as good as its gonna get. If anyone can test it out, let me know.

**Comment by billyors** [comment]
Thanks @lostb1t 🥳
Can confirm the latest release 0.20.2 resolves the issue for Android, Roku, and Web.

**Comment by lostb1t** [comment]
@billyors good to hear, tnx for testing
