### ISSUE TITLE
Lots of bugs

### ISSUE THREAD

**Issue by PilaScat** [lostb1t/replex#121]
iOS apps doesn't work, neither downloads, neither in LAN, very unstable experience
It's a shame since it makes a very beautiful home, I'm using SWAG for reverse proxy
For now I'll have to turn off the docker and go back to normal while waiting for fixes because half of my friends who watch have problems

**Comment by lostb1t** [comment]
What exactly do you mean with "doesnt work"

Ios works fine for me. Same as downloads. You on the latest plex ios version?

**Comment by eandrade92630** [comment]
None of my friends have issues. Sounds like you have a configuration problem.

**Comment by PilaScat** [comment]
All last version, this is my docker config:
![image](https://github.com/lostb1t/replex/assets/12989749/3bee02e8-ad04-4df4-9cd0-5c984ab4a39d)
This is my reverse proxy:
![image](https://github.com/lostb1t/replex/assets/12989749/f500852c-d6c1-4769-b11d-606347cd1d7f)
This my plex network setting (remote access disabled):
![image](https://github.com/lostb1t/replex/assets/12989749/635b65bd-3da0-4dce-967e-b468b55bfcd1)

**Comment by PilaScat** [comment]
Live TV especially doesn't work on iOS, is there a way to fix it?

**Comment by lostb1t** [comment]
> Live TV especially doesn't work on iOS, is there a way to fix it?

never checked live tv to be honest. you can check which paths plex uses for it and redirect those directly to plex server just like the library video files

**Comment by PilaScat** [comment]
I tried to do it but I can't, do you have any advise?On Feb 23, 2024 09:41, lostb1t ***@***.***> wrote:

Live TV especially doesn't work on iOS, is there a way to fix it?

never checked live tv to be honest. you can check which paths plex uses for it and redirect those directly to plex server just like the library video files

**Comment by PilaScat** [comment]
Seems the same as movies and tv

**Comment by PilaScat** [comment]
Seems an auth problem, now all iOS devices has this problem
![5938081368540037569_121](https://github.com/lostb1t/replex/assets/12989749/be2d9a40-34df-45a8-b042-8bdad102948d)
![5938081368540037567_121](https://github.com/lostb1t/replex/assets/12989749/6c7505a2-4bb4-4a1b-b2e5-aff350aa0ad6)
Logs can be helpful?

**Comment by PilaScat** [comment]
All seems fixed
