### ISSUE TITLE
Playlists break recommended on web

### ISSUE THREAD

**Issue by sahara101** [lostb1t/replex#122]
Hi, if I click on Movies recommended I get the error Something went wrong An unexpected error occurred. Log says Response status=401 Unauthorized 

Also, is it possible to maintain a trakt list order? I have a collection with same name on 2 libraries and are merged.

<img width="1413" alt="image" src="https://github.com/lostb1t/replex/assets/22507692/7f310931-0272-40e9-bc86-16e84371b9d9">

But the order is not the same as on the trakt list

**Comment by billyors** [comment]
I thought I was alone here. I'm seeing the same error and I think it started with one of the latest plex releases. 
Which client do you see the error with? Mine is only on the Web client. I haven't seen the issue with any other clients (Mobile, Roku, Android).

The trakt list thing, you should be able to append something like `?sort=released,desc` to the end of the URL that you're pulling from.

**Comment by sahara101** [comment]
I only tried the web one. 
?sort=released,desc would not work here as the list is created with future releases in order.

**Comment by billyors** [comment]
It looks like there might be a fix to this that was just released today. Once the docker version is pushed I can verify.
https://forums.plex.tv/t/plex-media-server/30447/616

> (Web) Home Screen content would not load when unauthenticated. (DISCO-1547)

**Comment by billyors** [comment]
Took a while to circle back to this. Updating PMS didn't resolve this. But I think I figured it out.

@lostb1t if you're still monitoring this channel. There seems to be an issue with the Web browser client where if you have pinned Playlists to the Home page, Replex displays "Something went wrong/ Unexpected Error". Unpinning Playlists from the Home page fixes the issue. This only seems to apply to the Web client.

**Comment by lostb1t** [comment]
@billyors thanks for the headsup, marked this as a bug
