### ISSUE TITLE
Landscape artwork in portrait tile

### ISSUE THREAD

**Issue by eandrade92630** [lostb1t/replex#126]
Something seems to have changed in Plex' code. On my Android TV (not happening on Mobile) client my hero rows appear in portrait mode with a possibly landscape poster, very blurry though so it could just be a portrait poster blown up. Anything I can do to help debug this?

**Comment by eandrade92630** [comment]
Also just noticed this only happens on the home screen. Individual libraries are fine.

**Comment by PilaScat** [comment]
same for me

**Comment by lostb1t** [comment]
duplicate of #120
