### ISSUE TITLE
What causes this to happen?

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#131]
Only one item will show up in my REPLEX Hero row and a couple of other merged rows. Clicking into and they are definitely all there, just won't show all together on the home screen. Here is an example.

![image](https://github.com/lostb1t/replex/assets/18123855/a2af9953-33ea-4966-a849-f92ff4f2245f)

`docker run -d --name=replex --rm -it -p 90:80 -l net.unraid.docker.icon='https://i.postimg.cc/T117HsQh/kindpng-7481011.png' -e REPLEX_HOST="http://192.168.1.22:32400" -e REPLEX_REDIRECT_STREAMS=true -e REPLEX_DISABLE_RELATED=true -e REPLEX_INCLUDE_WATCHED=true  -e REPLEX_HERO_ROWS=tv.toprated,tv.inprogress -e REPLEX_CACHE_ROWS=true -e REPLEX_CACHE_ROWS_REFRESH=true -e REPLEX_CACHE_TTL=1 ghcr.io/lostb1t/replex:latest`

**Comment by lostb1t** [comment]
interesting on which clients does this happen?

**Comment by jl94x4** [comment]
> interesting on which clients does this happen?

Only web app, nothing else

**Comment by lostb1t** [comment]
> > interesting on which clients does this happen?
> 
> 
> 
> Only web app, nothing else

which browser?

**Comment by jl94x4** [comment]
> > > interesting on which clients does this happen?
> > 
> > 
> > Only web app, nothing else
> 
> which browser?

Edge

**Comment by jl94x4** [comment]
Did you manage to replicate this? @lostb1t

**Comment by lostb1t** [comment]
i cant actually, tested all big browsers and working fine for me (macos)
