### ISSUE TITLE
Use replex to support AI Recommendations ?

### ISSUE THREAD

**Issue by stevezau** [lostb1t/replex#132]
Hi, I had an idea i wanted to float by you. I haven't through it out yet but figured ill just dump whats in my mind.. 

i came across https://github.com/rocstack/plex-recommendations-ai today.

One of the problems is how do you do per user recommendations without it becoming messy. (https://github.com/rocstack/plex-recommendations-ai/issues/4) 

I was thinking.. Maybe we can rewrite the URL.. I am assuming when you hit the home/movies/tv plex UI will hit the plex server per collection.. 

Could we rewrite that URL to someone show the AI recommendation for that user?

WDYT?

**Comment by lostb1t** [comment]
Not sure what the issue is here. in theory you can create an  (AI) collection for each user and then  restrict those collections to the appropriate user with plex labels.

So not sure what replex role in this?

**Comment by stevezau** [comment]
@lostb1t, how would you "restrict those collections to the appropriate user with plex label"? I didn't think Plex had that level of access controls?

**Comment by jl94x4** [comment]
> @lostb1t, how would you "restrict those collections to the appropriate user with plex label"? I didn't think Plex had that level of access controls?

Labels

**Comment by PierreDurrr** [comment]
Sure it's possible to use labels, but you will not be able to pin it on home only for desired user

**Comment by PierreDurrr** [comment]
Hum nope. Sorry but i have to say you're wrong. Collection will still be visible for other users

**Comment by lostb1t** [comment]
Forgot about that but @PierreDurrr is correct, panels do not work fok for hubs. One di the weird plex decision.
I would call it a bug, plex a feature.

I had this feature in replex. But removed it.

I could bring it back, if a user does not have access to an collection it will not show as a hub/recommended row

**Comment by lostb1t** [comment]
This feature has been released: https://github.com/lostb1t/replex/releases/tag/0.25.0

**Comment by stevezau** [comment]
Great, ill test this out. Thanks!!

**Comment by stevezau** [comment]
@lostb1t i assume it will cache the permissions? Just concerned on the speed if I have 20 users, each with their own collection.

**Comment by lostb1t** [comment]
@stevezau its actually not that performance heavy. All it does is an extra call to the collection page to see if the user has access to collections.

That said, yes its cached. And you can also disable this feature if you want.

**Comment by PierreDurrr** [comment]
> Hi, I had an idea i wanted to float by you. I haven't through it out yet but figured ill just dump whats in my mind..
> 
> i came across https://github.com/rocstack/plex-recommendations-ai today.
> 
> One of the problems is how do you do per user recommendations without it becoming messy. ([rocstack/plex-recommendations-ai#4](https://github.com/rocstack/plex-recommendations-ai/issues/4))
> 
> I was thinking.. Maybe we can rewrite the URL.. I am assuming when you hit the home/movies/tv plex UI will hit the plex server per collection..
> 
> Could we rewrite that URL to someone show the AI recommendation for that user?
> 
> WDYT?

You can also use couchmoney.tv to achieve a list of recommendations based on history (and maybe also ratings)

**Comment by stevezau** [comment]
@PierreDurrr i want to create a recommendations for each user based on their watch history. I don't think couchmoney.tv can do that ?

**Comment by lostb1t** [comment]
@stevezau @PierreDurrr could you move this into a discussion? i think other users will benefit from this discussion in the future

**Comment by PierreDurrr** [comment]
There you go [https://github.com/lostb1t/replex/discussions/136](https://github.com/lostb1t/replex/discussions/136)

**Comment by stevezau** [comment]
@PierreDurrr i noticed in #136 you used couchmoney.tv to generate the recommendations. How did that work out for you? I am trying to decide if I use chatgpt, perplexity or couchmoney.tv or a combo of all. Looking to learn from any of your learnings.. if any. Thanks!!

**Comment by PierreDurrr** [comment]
> @PierreDurrr i noticed in #136 you used couchmoney.tv to generate the recommendations. How did that work out for you? I am trying to decide if I use chatgpt, perplexity or couchmoney.tv or a combo of all. Looking to learn from any of your learnings.. if any. Thanks!!

It's working pretty well for my needs. Just try, and see if it's doing what you are looking for.
And, it's free 😉

**Comment by stevezau** [comment]
Thanks @PierreDurrr.. I had a look at https://couchmoney.tv/ and it seems to only work if you "rate" a show or movie vs giving recommendations based on your watch history. So if my users don't rate then i don't think this will work? Are you relying on your users rating?

**Comment by stevezau** [comment]
@PierreDurrr i think it might work even just based on watched status. I am trying to find who is the developer/owner to verify.
