### ISSUE TITLE
REPLEX_TOKEN

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#134]
Saw this new in the description, did something change to require this for hero's to work now?

Do we need to supply the token? What breaks if we do not?

Also this is in the settings on the readme but doesn't make much sense, can you explain what it means?

```recommendations. Rows from sifferent sections are interlewved into one.```

**Comment by lostb1t** [comment]
Found put that plex hero art  endpoint is buggy, if plex has a cached version then it doesn't need a plex token. But if it isn't cached it needs an token from the server admin.

So new media wasnt be an issue as its requested a lot by people. But old
media would have missing hero images

**Comment by lostb1t** [comment]
and yes making this a breaking change. Replex will not start without it

**Comment by PilaScat** [comment]
updated and added token, but:
![image](https://github.com/user-attachments/assets/f1297d64-c06b-444e-9d93-5b05b30c0a32)

**Comment by lostb1t** [comment]
> updated and added token, but:
> 
> ![image](https://github.com/user-attachments/assets/f1297d64-c06b-444e-9d93-5b05b30c0a32)
> 
> 

@PilaScat sure its valid? nothing in the logs a about not able to retrieve metadata?

**Comment by PilaScat** [comment]
nothing about metadata, but this:
![image](https://github.com/user-attachments/assets/db2ed654-1b2c-442b-9943-4557aae9de4a)

**Comment by lostb1t** [comment]
hmm seems tour replex domain
might not be reachable from the replex container itself.

Could you share the whole path from the 404 log response? i need that url argument (you can hide the domain name)

**Comment by PilaScat** [comment]
is strange because I haven't changed anything:
![image](https://github.com/user-attachments/assets/b22efed4-9f36-4042-9f2d-ac4f2953a96d)

**Comment by lostb1t** [comment]
Code has changed.

Could you try to ping your replex domain from the machine you are hosting replex?

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/8e30d439-831d-45ca-813b-08473747283e)

**Comment by lostb1t** [comment]
@PilaScat pushed some changes, could you give it a go?

**Comment by PilaScat** [comment]
> @PilaScat pushed some changes, could you give it a go?
fixed thanks
