### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at src/transform.rs:268:18:

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#138]
Getting this on Movies Recommendations page however it only happens on the admin account, managed users seems fine?

![image](https://github.com/user-attachments/assets/9ecfad0e-4385-481d-87e7-2793573a3caf)

`thread 'tokio-runtime-worker' panicked at src/transform.rs:268:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/transform.rs:268:18:
called `Option::unwrap()` on a `None` value`

Doesn't happen with TV

**Comment by jl94x4** [comment]
Does this on mobile

![Screenshot_20240714_203352_Plex](https://github.com/user-attachments/assets/d3f9af42-3f6e-4454-b77f-35aa17301f3c)

**Comment by jl94x4** [comment]
Still getting this issue even on the newest release

**Comment by lostb1t** [comment]
@jl94x4 weird, could you give the latest another go?

**Comment by jl94x4** [comment]
There we go. Looks to be working now!
