### ISSUE TITLE
Forwarding "real" IP address

### ISSUE THREAD

**Issue by cakarlen** [lostb1t/replex#142]
Does this project have the ability to preserve the "real" IP address of clients using Plex to reflect on the Plex dashboard correctly?

Currently, I'm using Caddy to reverse proxy Plex while following the steps listed in this repo and ensured I'm forwarding the necessary headers to preserve the IP. Plex works on all tested clients and can confirm that I can access Plex remotely, but all clients (including on LAN) are showing as remote, instead of the true IP address of the client.

**Comment by lostb1t** [comment]
yeah this is a bug. Im forwarding all correct headers but plex still uses the wrong ip. Marking this as a bug, will look into it soon.

**Comment by lostb1t** [comment]
@cakarlen actually this seems
to work.

Could you post a trace log, the messages should contain a forwarded-for header with your correct ip.

you can enable tracing by adding a env variable with RUST_LOG="info,replex=tracing"

**Comment by lostb1t** [comment]
> Ah, you're correct. I connected to a VPN and can confirm that the IP shown in the Plex dashboard was my public IP while on the VPN. I think the problem I realized is that if I talk to Plex locally (while on LAN), the Plex dashboard will show the container IP address (ex: 172.18.0.5), instead of my LAN IP address (ex: 192.168.1.10). 
> 
> 
> 
> Is there a way to fix that issue?

where does it show that? can you post a debug log?

**Comment by lostb1t** [comment]
Also im unsure how "local" ever happens. All clients connect to your custom server url. Only the web admin might be "local" do you have any other values in the custom server url?

**Comment by cakarlen** [comment]
I don't have any other custom server URLs other than my public URL (ex: https://plex.mydomain.com). 

I've added the `RUST_LOG` env variable, but should I expect the trace logs to write to stdout/stderr or to a file? Sorry, not too familiar with Rust inter-workings.

**Comment by lostb1t** [comment]
no worries, yeah should show up there

**Comment by lostb1t** [comment]
but the dashboard says otherwise?

**Comment by cakarlen** [comment]
That is correct. Plex dashboard will show the replex container IP address instead. I can provide my Caddyfile (or any other file for that matter) if needed to help troubleshoot.

**Comment by lostb1t** [comment]
could you maybe add the ip ir subnet mask (192.168.1.1/24) to plex LAN networks? (under network) and see if that changes anything

**Comment by cakarlen** [comment]
I actually did that first thing when I setup replex. Here is what I have configured under "LAN networks". Notice the `172.18.0.0/16` entry to account for any _local_ device watching Plex media, but again, the Plex dashboard shows the replex container IP despite this:

![image](https://github.com/user-attachments/assets/1cd2c6ee-057e-4792-a03b-685df42bb1fc)

![image](https://github.com/user-attachments/assets/eaea1312-c0e4-4764-a5ff-2a78ab558046)

**Comment by cakarlen** [comment]
After doing some digging, I noticed folks who have this same problem using just Plex were able to solve this issue by running the Plex container using the host network (`network_mode: host`). Since replex is not compatible with that configuration, I'm wondering if there's another way to accomplish the same thing.

**Comment by jl94x4** [comment]
On mine, on dashboard it shows my public address and not the container address/local

**Comment by jl94x4** [comment]
> After doing some digging, I noticed folks who have this same problem using just Plex were able to solve this issue by running the Plex container using the host network (`network_mode: host`). Since replex is not compatible with that configuration, I'm wondering if there's another way to accomplish the same thing.

My Plex is running as host and REPLEX is working fine?

**Comment by lostb1t** [comment]
> After doing some digging, I noticed folks who have this same problem using just Plex were able to solve this issue by running the Plex container using the host network (`network_mode: host`). Since replex is not compatible with that configuration, I'm wondering if there's another way to accomplish the same thing.

yes this seems like a plex bug.

Unfortunately host mode does not work for replex as plex will  connect direct to plex itself and bypass replex

**Comment by lostb1t** [comment]
@jl94x4 it depends on the client. Some clients dint allow unsecured connections so always need https. Some dont and will connect directly to plex when in host mode

**Comment by cakarlen** [comment]
@lostb1t Do you have this problem? If not, would you be able to share a redacted Dockerfile or Caddyfile since if that works for you, it should work for me (and maybe others)?

**Comment by lostb1t** [comment]
its not a configuration issue, its a plex issue. I have the same. Plex does
not listen the forwarded headers when its a local ip 🤷‍♂️

**Comment by cakarlen** [comment]
Ah ok, gotcha. Well if this is truly a Plex issue, I think we can close this issue out. Thanks for helping troubleshoot this
