### ISSUE TITLE
UNRAID Community App

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#145]
This is more of a request, but would it be possible for you to make this an UNRAID community app as UNRAID is quite popular among Plex users.

**Comment by lostb1t** [comment]
theres a template here: https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/replex.xml

tho the config is outdated

**Comment by lostb1t** [comment]
> Created pull request with updated template: https://github.com/selfhosters/unRAID-CA-templates/pull/503

awesome

**Comment by jl94x4** [comment]
How do I use the template on UNRAID, though?

**Comment by PilaScat** [comment]
> How do I use the template on UNRAID, though?

You can add it to dockerMan manually, but if you don't feel like it I recommend you wait, it will probably be on CA in a few days

**Comment by PilaScat** [comment]
Online now
