### ISSUE TITLE
Playback error on many devices after yesterday's updates

### ISSUE THREAD

**Issue by PilaScat** [lostb1t/replex#146]
My logs are full of this:
![image](https://github.com/user-attachments/assets/3407b874-9aa2-4970-802a-2d3d51a211fc)

**Comment by PilaScat** [comment]
Temporarily downgraded to 0.27.2

**Comment by lostb1t** [comment]
thanks for the report, fixed in 0.27.8

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/23f7cb15-0130-4d55-a64c-da18ea0ea18a)
Still problematic

**Comment by lostb1t** [comment]
@PilaScat what features dontou have enabled? can you post your envs?

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/70225496-5322-4682-a1b3-610a8a790dcc)
only this

**Comment by lostb1t** [comment]
@PilaScat pushed a fix could you try out latest?

**Comment by PilaScat** [comment]
Seems working

**Comment by jl94x4** [comment]
> ![image](https://private-user-images.githubusercontent.com/12989749/350467066-70225496-5322-4682-a1b3-610a8a790dcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDk1OTksIm5iZiI6MTcyMTQwOTI5OSwicGF0aCI6Ii8xMjk4OTc0OS8zNTA0NjcwNjYtNzAyMjU0OTYtNTMyMi00NjgyLWExYjMtNjEwYThhNzkwZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE3MTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMDI0MzYzOTYwMmI3Y2UyNDI4MWUxZDdhMGRmOTg3OWE5MWJmNjkwMTY2YjZiY2M4ZTU5ZWUzYmRjY2NkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gz04Hw51Z0sWCBJ1dSscHp4g23mwqkxbTJoNTqHi36Q) only this

Hey! Can you show me your community apps config for UNRAID?

**Comment by PilaScat** [comment]
> Hey! Can you show me your community apps config for UNRAID?

It's very simple actually, those two things plus host, port, and token
