### ISSUE TITLE
Blank hero images

### ISSUE THREAD

**Issue by PilaScat** [lostb1t/replex#159]
All of them, disappeared

**Comment by PierreDurrr** [comment]
Same here. OK on Nvidia Shield, and Android phone app. OK using directly replex ip/domain.
Blank when using app.plex.tv

**Comment by lostb1t** [comment]
hm seems they might have released a new web version that broke it. Will have to investigate

**Comment by lostb1t** [comment]
so i checked and this seems unfixable from my side. Seems plex either fucked it up by accident or put a stop to it on purpose

**Comment by PilaScat** [comment]
oh no

**Comment by lostb1t** [comment]
Good news, a fellow replexer on discord found a hack to make it work again. Fixed on latest.

**Comment by PilaScat** [comment]
![image](https://github.com/user-attachments/assets/da2644c2-4bcb-45a0-8b26-540d8ccde6cb)
returned, but only on windows app, web and android is working

**Comment by erphise** [comment]
Still happening the same on windows app as @PilaScat mentioned
