### ISSUE TITLE
Ability to hide hubs from server admin

### ISSUE THREAD

**Issue by BlakeB415** [lostb1t/replex#163]
I would like to be able to hide user-specific hubs from my home page. This could be a label applied to the collections that will filter out the hub if the user the server admin.

**Comment by lostb1t** [comment]
Im not sure if i understand as there is already an option to hide a hub from either the admin homepage or friends homepage. (settings -> manage -> Libraries)

**Comment by BlakeB415** [comment]
> Im not sure if i understand as there is already an plex option to hide a hub from either the admin homepage or friends homepage. (settings -> manage -> Libraries)

Oh yeah, this should work. You can't do it with Library Recommended although that doesn't matter for my use case.
