### ISSUE TITLE
Promoted hubs fail to load

### ISSUE THREAD

**Issue by lostb1t** [lostb1t/replex#33]
`replex  | 2023-08-11T18:06:07.339552Z ERROR replex::routes: Failed to get plex response error=Other(Error("expected value", line: 1, column: 1)) uri=/hubs/promoted?pinnedContentDirectoryID=1%2C14%2C2%2C6%2C3%2C10%2C9%2C11%2C15%2C7%2Cplaylists&includeMeta=1&excludeFields=summary&includeStations=1&includeLibraryPlaylists=1&includeRecentChannels=1&excludeContinueWatching=1&X-Plex-Product=Plex+Web&X-Plex-Version=4.108.0&X-Plex-Client-Identifier=fjdme9hubdqcelq1frh6cky7&X-Plex-Platform=Safari&X-Plex-Platform-Version=16.6&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Name=Safari&X-Plex-Device-Screen-Resolution=1513x869%2C1680x1050&X-Plex-Token=SECRET&X-Plex-Provider-Version=6.3&X-Plex-Text-Format=plain&X-Plex-Drm=fairplay&X-Plex-Language=en&contentDirectoryID=1%2C14%2C2%2C6%2C3%2C10%2C9%2C11%2C15%2C7%2Cplaylists&includeGuids=1&count=24`

**Comment by JesseWebDotCom** [comment]
Added REPLEX_CACHE=0, rebuilt replex, refreshed the plex web client, and now the only recommendations displayed on the home page are:
* Continue Watching
* Recent Channels
* And all the "On Plex" and "Discover" recommendations

**Comment by JesseWebDotCom** [comment]
Don't think so - how do I check?

Also, just did this test:

* unchecked every recommendation from every library
* only checked "Recently release movies" form "Library recommended" and home
* went to home page, recommendation was not there
* went to movie library, recommendation was there
* went back to home page, recommendation was there

**Comment by JesseWebDotCom** [comment]
Unpinned everything and only added "Recently released movies" and pinned the movies library and now it shows in hero mode when viewing through replex and poster mode when viewed through plex.

**Comment by JesseWebDotCom** [comment]
I think it breaks when I have any recommendations displayed on a library of type "other" videos.  Testing.

**Comment by JesseWebDotCom** [comment]
I can't get it to display hero mode any more.  But every now and then I get the error:
```
Something went wrong
There was an error loading your home screen. Please try again in a few minutes.
```

**Comment by JesseWebDotCom** [comment]
Now I get that error all the time on the home page in both replex and plex.

**Comment by JesseWebDotCom** [comment]
Same issue:
```
replex  | 2023-08-14T00:27:35.996537Z ERROR Request{remote_addr=socket://172.22.0.1:36008 version=HTTP/1.1 method=GET headers={"host": "127.0.0.1:3001", "connection": "keep-alive", "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Microsoft Edge\";v=\"115\", \"Chromium\";v=\"115\"", "accept": "application/json, text/plain, */*", "accept-language": "en", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203", "sec-ch-ua-platform": "\"Windows\"", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:3001/web/index.html", "accept-encoding": "gzip, deflate, br"} path=http://127.0.0.1:3001/hubs/sections/1?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.108.0&X-Plex-Client-Identifier=i02mqrm3i2a33cdoz0c988ok&X-Plex-Platform=Microsoft%20Edge&X-Plex-Platform-Version=115.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Microsoft%20Edge&X-Plex-Device-Screen-Resolution=1625x939%2C1680x1050&X-Plex-Token=SECRET-Plex-Provider-Version=6.3&X-Plex-Text-Format=plain&X-Plex-Drm=playready&X-Plex-Language=en span.kind="server" service.name="replex"}: replex::routes: Failed to get plex response error=Other(Error("expected value", line: 1, column: 1)) uri=/hubs/sections/1?includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex+Web&X-Plex-Version=4.108.0&X-Plex-Client-Identifier=i02mqrm3i2a33cdoz0c988ok&X-Plex-Platform=Microsoft+Edge&X-Plex-Platform-Version=115.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Microsoft+Edge&X-Plex-Device-Screen-Resolution=1625x939%2C1680x1050&X-Plex-Token=SECRET-Plex-Provider-Version=6.3&X-Plex-Text-Format=plain&X-Plex-Drm=playready&X-Plex-Language=en&count=24&includeGuids=1
```

**Comment by Serph91P** [comment]
> Ive added some extra logging. If you could retry and paste the output of the log here that would be great

I think I have the same error nothing shows everywhere even with only movies or something pinned:

````
2023-09-05 14:02:21
 2023-09-05T14:02:21.894491Z ERROR replex::routes: Failed to get plex response status=404 uri=http://redacted/hubs/sections/1?includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex+Web&X-Plex-Version=4.108.0&X-Plex-Client-Identifier=redactedr&X-Plex-Platform=Firefox&X-Plex-Platform-Version=117.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=1920x927%2C1920x1080&X-Plex-Token=redactedX-Plex-Provider-Version=6.3&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en&count=50&includeGuids=1
2023-09-05 14:02:21
 2023-09-05T14:02:21.895598Z ERROR salvo_core::error: anyhow error occurred error=code: 500 Internal Server Errorname: Internal Server Errorbrief: "The server encountered an internal error while processing this request."detail: Nonecause: None
