### ISSUE TITLE
collections with random sort order

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#49]
Random sort on hero style when more than 1 collections are merged seems to not work, seems to only randomise the first on the row, everything else stays the same for some reason.

**Comment by jl94x4** [comment]
Also clicking the collection from home shows an error

![image](https://github.com/sarendsen/replex/assets/18123855/0975dbd7-e0c4-4c72-bec1-79b2b7af240d)

This doesn't error for any other collections with normal poster layout.

**Comment by jl94x4** [comment]
Seeing this on plex web haven't tried any other devices.

**Comment by jl94x4** [comment]
docker run --rm -it -p 90:80 -e REPLEX_HOST="http://116.202.237.239:32400" -e REPLEX_TMDB_API_KEY=a5dfafcf872b71d747deeca3c1cfc139 -e REPLEX_DISABLE_USER_STATE=true -e REPLEX_DISABLE_LEAF_COUNT=true -e RUST_LOG=“info,replex=debug -e INCLUDE_WATCHED=0 ghcr.io/sarendsen/replex:latest

**Comment by jl94x4** [comment]
Random doesn't seem to be working on any of my collections.

**Comment by jl94x4** [comment]
When you click on the collection it shows as random each time, but when refreshing the home screen the rows don't show a different order each time when using Replex however with the native plex app they randomise quite often "live"

**Comment by jl94x4** [comment]
![image](https://github.com/sarendsen/replex/assets/18123855/1292f135-debe-4fb3-9c75-1d557effa0eb)

https://app.plex.tv/desktop/#!/media/48f6e63f630d2c7d444e4182b877de7edeb547df/com.plexapp.plugins.library?key=%2Freplex%2Flibrary%2Fcollections%2F%2Freplex%2Freplex494159%2C494178%2C494179%2C494180%2Fchildren%3FcontentDirectoryID%3D6%26pinnedContentDirectoryID%3D6%252C9%252C10%252C4%252C5%252C3%252C18%252C19&title=Trending%20on%20[Plex](https://app.plex.tv/desktop/#!/media/48f6e63f630d2c7d444e4182b877de7edeb547df/com.plexapp.plugins.library?key=%2Freplex%2Flibrary%2Fcollections%2F%2Freplex%2Freplex494159%2C494178%2C494179%2C494180%2Fchildren%3FcontentDirectoryID%3D6%26pinnedContentDirectoryID%3D6%252C9%252C10%252C4%252C5%252C3%252C18%252C19&title=Trending%20on%20Plexified&source=server%3A%2F%2F48f6e63f630d2c7d444e4182b877de7edeb547df%2Fcom.plexapp.plugins.library&pageType=list&context=home%3Ahub.custom.collection~1)ified&source=server%3A%2F%2F48f6e63f630d2c7d444e4182b877de7edeb547df%2Fcom.plexapp.plugins.library&pageType=list&context=home%3Ahub.custom.collection~1

**Comment by jl94x4** [comment]
I see this is working on a singular Movies collection I have pinned to the home screen.

It doesn't work when more than 1 library has the same collection, all pinned to the home screen. Is this an impossible thing to get working or a bug?

**Comment by jl94x4** [comment]
`docker run --rm -it -p 90:80 -e REPLEX_HOST="http://ip:32400" -e REPLEX_TMDB_API_KEY=<api> -e REPLEX_CACHE_TTL=30 -e REPLEX_CACHE_ROWS=true  -e RUST_LOG=“info,replex=debug ghcr.io/sarendsen/replex:latest`

I'm using the above cmd

**Comment by jl94x4** [comment]
`docker run --rm -it -p 90:80 -e REPLEX_HOST="http://ip:32400" -e REPLEX_TMDB_API_KEY=<api> -e REPLEX_CACHE_TTL=0 -e REPLEX_CACHE_ROWS=0  -e RUST_LOG=“info,replex=debug ghcr.io/sarendsen/replex:latest`

Running this now, tried restarting, the mixed/merged collections still don't refresh/randomize.

**Comment by jl94x4** [comment]
Random rows are working without Replex for me.

**Comment by lostb1t** [comment]
Cache has been removed for rows so this should work correctly
