### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by LarveyOfficial** [lostb1t/replex#69]
I've been trying to figure out/learn how to actually use RePlex with my plex instance. I've gotten to the point where i can go to the RePlex webpage, but it just looks like my normal plex. No Trending, No hero style, just normal Plex.

How do I actually use it? How can I get it to look like the one in the Readme?

**Comment by LarveyOfficial** [comment]
I can confirm the actual proxy is working as enabling REPLEX_FORCE_MAXIMUM_QUALITY does actually force the maximum quality

**Comment by LarveyOfficial** [comment]
Ok. after some help on Reddit I was able to figure out how to use it.

But I'm having an issue where it doesn't work if im on my local network (currently remote so whenever I turn on my VPN Replex wont work, sometimes even by using IP:PORT)

Whenever im on a local connection app.plex.tv, my domain, and clients do not use the replex HERO style. Only whenever im remote.

**Comment by LarveyOfficial** [comment]
Ok, Im gonna close this. Figured it out. VPNs don't play nice with it lol.
But got it to work locally now :D

**Comment by jl94x4** [comment]
> Ok, Im gonna close this. Figured it out. VPNs don't play nice with it lol. But got it to work locally now :D

Glad you manged to sort it!

**Comment by PierreDurrr** [comment]
> Ok, Im gonna close this. Figured it out. VPNs don't play nice with it lol. But got it to work locally now :D

Can i ask how you got it working locally ?

**Comment by LarveyOfficial** [comment]
> > Ok, Im gonna close this. Figured it out. VPNs don't play nice with it lol. But got it to work locally now :D
> 
> Can i ask how you got it working locally ?

Sadly. It wasn't true local. It ended up making all my local connections use my domain, so everything was technically external. It also caused issues with not being able to rewind, as well as playback just randomly stopping. So I ended up just not using it...
