### ISSUE TITLE
Continue Watching

### ISSUE THREAD

**Issue by PierreDurrr** [lostb1t/replex#78]
Is there a way to convert "Continue Watching" row to hero style ?
Can't find it...

**Comment by PierreDurrr** [comment]
Oops, just saw that it was stated in the readme... Sorry !
Closing now.

**Comment by jl94x4** [comment]
> Oops, just saw that it was stated in the readme... Sorry ! Closing now.

Hi could you tell me what the hub identifier is for continue watching? Thanks!
