### ISSUE TITLE
Images not showing correctly after 0.18.27

### ISSUE THREAD

**Issue by eandrade92630** [lostb1t/replex#99]
I had to roll back my container to 0.18.27 because I noticed on Android TV it was showing full sized and cut off posters for hero rows, I believe on other devices it had the right sized images but the images were completely different on the home screen from when browsing on a specific library such as "movies".

**Comment by eandrade92630** [comment]
Actually 0.18.30 seems to be the last good version after double checking

**Comment by eandrade92630** [comment]
Can't remember but I wanna say 11?
Also on .30 noticing on my phone (Android 14) that on the home screen the artwork is a good size but browsing specific libraries the artwork is slightly cut off.

**Comment by eandrade92630** [comment]
Ahh ok. Hadn't noticed it before but it's definitely broken on Android TV where on older versions hero rows works well. Are there any logs I should look for I could provide you?

**Comment by eandrade92630** [comment]
![PXL_20231028_092243732](https://github.com/lostb1t/replex/assets/117824511/a5cf7737-3111-40a7-80e0-3172838fd984)
![PXL_20231028_093142794](https://github.com/lostb1t/replex/assets/117824511/98c76ce4-d3ea-486c-a760-881995680418)

Here's one photo of the home screen on the latest version of replex and one photo of the movie library on replex version 0.18.30

And here's the log on the latest version
https://pastebin.com/vsTVJd1r

**Comment by eandrade92630** [comment]
Nope. This didn't work. Yes it's the Onn 4K. I'll try to pull logs again tonight. Anything I should look for? If I can grep for something in specific it could make the log much shorter. Otherwise I'll try to capture logs at a time when there's less traffic.

**Comment by eandrade92630** [comment]
In fact this last update made things worst. The art work is majorly cut off both on the home screen and libraries. Before only the home screen had huge cut off art work now it's libraries as well.

**Comment by eandrade92630** [comment]
I grepped Onn in this log. Hopefully it shows you some useful information.
https://drive.google.com/file/d/1HRwIf9JC8wUDR_OWizgkJ-dRnw4IbA-x/view?usp=drivesdk

**Comment by eandrade92630** [comment]
The problem persists even after a restart yes. And yes 0.18.30 was the last working version (at least on the onn box). I'm currently on the latest version and today I noticed that even on my fire tv I am having this issue.

**Comment by eandrade92630** [comment]
I'll roll back to 0.18.30 and 0.18.31 when I get a chance just to double check, but when I noticed the issue I did test multiple versions and noticed 0.18.30 was in fact the last version I tested where hero rows art worked correctly.

**Comment by eandrade92630** [comment]
I'm on the latest build. Just hopped on my Xbox today and thought to check it out and sure enough I'm having this issue on my Xbox as well, oddly though it's only affecting series, movies look fine.

**Comment by eandrade92630** [comment]
Oh wait. Hadn't seen there was a newer build. Will test and get back to you.

**Comment by eandrade92630** [comment]
Yes, here's the log.
https://docs.google.com/document/d/1R0-ZK7uMlm_SwSWYoPj9zshY1u5Py9yFnLqdQu2MFAc/edit?usp=drivesdk

**Comment by eandrade92630** [comment]
Sorry 😂 idk how that happened
https://drive.google.com/file/d/1IxhhZY5emtfHCedo1-JvEYttvBDtsNsQ/view?usp=drivesdk
Note WARN was grepped here. I'm not sure if you need any extra information.

**Comment by eandrade92630** [comment]
Here's a full log without grepping. Seems I'm getting a lot of 401s. Also the hero art started working again in this latest version for most but not all titles. There's a few titles here and there that are still having issues. Will check on my Xbox when I get the chance to see if it's still an issue there as well.

**Comment by eandrade92630** [comment]
So on the latest version it seems to be working much better, though I still find a couple titles here and there that don't have the correct art. I tried reading the logs but there's so much and I couldn't really find anything that popped out. Is there anything in specific I should be looking for?

**Comment by lostb1t** [comment]
i know whats happening. plex is throttling the metadata requests. just have to find some time to fix it :)

**Comment by eandrade92630** [comment]
Just two (2 movie and 2 series rows technically but combined with replex)

**Comment by jl94x4** [comment]
I am also experiencing this issue on Chromecast w/Google TV.

**Comment by lostb1t** [comment]
Alright ive added a retry function for the 401's
Let me know

**Comment by eandrade92630** [comment]
I'm still seeing incorrect art work on some titles. To what severity though I don't know yet as it can change depending on the titles and my collections constantly rotate. I'll give it a good test and let you know. It's always the same titles missing the art work though, reloading Plex doesn't change things.

**Comment by lostb1t** [comment]
can you post a log?

**Comment by eandrade92630** [comment]
https://drive.google.com/file/d/1O6d_Y12ykqox_O0ATGgzcC4vxMO-ot6T/view?usp=drivesdk
Let me know if you need more

**Comment by lostb1t** [comment]
Adding more retries will slow it to an halt. Instead I removed caching for metadata that returns 401. So it will try to request again when plex client does a refresh.

Im afraid I cannot do anything else for now. Will close this issue.
